const eventList = [
  {
    id: 1,
    img: '/1.jpg',
    title: 'INCUBUS ASIA TOUR',
    alt: 'INCUBUS',
    date: '23 April 2024',
    price: 'Rp450.000',
    organize: 'CK Star Enterntaiment',
  },
  {
    id: 2,
    img: '/2.jpg',
    title: 'URBANISME SHOWCASE BY EAR SUN',
    alt: 'URBANISME SHOWCASE BY EAR SUN',
    date: '23 Juni 2024',
    price: 'Rp150.000',
    organize: 'EAR SUN',
  },
  {
    id: 3,
    img: '/3.jpg',
    title: 'HOMOLUDENS: Nyong Alga Intimate Concert',
    date: '23 Mei 2024',
    price: 'Rp100.000',
    organize: 'EDURA UNJ',
  },
  {
    id: 4,
    img: '/4.jpg',
    title: 'Foam Party with Bagus Wirata',
    alt: 'Foam Party with Bagus Wirata',
    date: '03 Februari 2024',
    price: 'Rp40.000',
    organize: 'Amerta Creative',
  },
  {
    id: 5,
    img: '/5.png',
    title: 'Jeff Bernat Asia Tour 2024',
    alt: 'Jeff Bernat Asia Tour 2024',
    date: '3 Maret 2024',
    price: 'Rp650.000',
    organize: 'Otello Asia',
  },
  {
    id: 6,
    img: '/6.png',
    title: 'JOYLAND BALI 2024',
    alt: 'JOYLAND BALI 2024',
    date: '03 April 2024',
    price: 'Rp450.000',
    organize: 'Plainsong Live',
  },
  {
    id: 7,
    img: '/7.jpg',
    title: 'TOSCA PENSI XXVI',
    alt: 'TOSCA PENSI XXVI',
    date: '03 Maret 2024',
    price: 'Rp45.000',
    organize: 'SMA Plus Pembangunan Jaya',
  },
  {
    id: 8,
    img: '/8.jpg',
    title: 'GOBLIN MODE - SOUNDS FROM THE CORNER',
    alt: 'GOBLIN MODE - SOUNDS FROM THE CORNER',
    date: '23 April 2024',
    price: 'Rp150.000',
    organize: 'KRAPELA',
  },
];

export default eventList;
